#!/bin/bash

[ -n "$VERBOSE" ] && echo "preinst called with argument \`$1'" >&2
[ -n "$VERBOSE" ] && set -x

#
# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#
case "$1" in
    install)
    ;;

    upgrade)

        OLD_TIMESTAMP="$2"
        OLD_VERSION=$( echo $OLD_TIMESTAMP | cut -d'.' -f1-3 )

        mkdir -p __PREFIX__/kafka/kafka-${OLD_TIMESTAMP}/
        mv __PREFIX__/kafka/kafka-${OLD_VERSION}/config __PREFIX__/kafka/kafka-${OLD_TIMESTAMP}/config
        if [ -d __PREFIX__/kafka/kafka-$OLD_VERSION/logs ]; then
           rm -rf __PREFIX__/kafka/kafka-$OLD_VERSION/logs
        fi
        DAEMON_CONF=__PREFIX__/conf/daemon.conf

    	if [ -f "$DAEMON_CONF" ]; then
			MAPR_USER=$( awk -F = '$1 == "mapr.daemon.user" { print $2 }' $DAEMON_CONF)
			MAPR_GROUP=$( awk -F = '$1 == "mapr.daemon.group" { print $2 }' $DAEMON_CONF)
            if [ ! -z "$MAPR_USER" ]; then
				chown -R ${MAPR_USER}:${MAPR_GROUP} __PREFIX__/kafka/kafka-${OLD_TIMESTAMP}
            fi
        fi

    ;;
    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac




